name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[test]
          pip install black flake8 isort mypy

      - name: Verify installations
        run: |
          python -m black --version
          python -m isort --version
          python -m flake8 --version
          python -m mypy --version

      - name: Run tests
        run: |
          pytest -v tests/
          pytest --cov=app --cov-report=xml tests/

      - name: Run linters
        run: |
          echo "=== Running Black ==="
          black --check app/ tests/ || echo "Black check failed"
          
          echo "=== Running isort ==="
          isort --check-only app/ tests/ || echo "isort check failed"
          
          echo "=== Running flake8 ==="
          flake8 app/ tests/ || echo "flake8 check failed"
          
          echo "=== Running mypy ==="
          mypy app/ tests/ || echo "mypy check failed"

      - name: Upload coverage
        if: always()
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests